import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useMemo, useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { Chip, PageHeader, SathiScreen, sharedStyles } from "@/components/sathi-ui";
import { trpc } from "@/lib/trpc";
import { useStudentSathi } from "@/lib/studentsathi-store";
import { useColors } from "@/hooks/use-colors";

const PROMPTS = ["Find scholarships for my course", "What documents should I prepare?", "Explain eligibility in Hindi"];

export default function AssistantScreen() {
  const colors = useColors(); const { state, addAssistantMessage } = useStudentSathi(); const [message, setMessage] = useState(""); const chat = trpc.assistant.chat.useMutation();
  const profileSummary = useMemo(() => ({ educationLevel: state.profile.educationLevel, course: state.profile.course, state: state.profile.state, category: state.profile.category, incomeBand: state.profile.incomeBand }), [state.profile]);
  const send = async (content = message) => {
    const trimmed = content.trim(); if (!trimmed || chat.isPending) return;
    addAssistantMessage({ id: `user-${Date.now()}`, role: "user", content: trimmed, createdAt: new Date().toISOString() }); setMessage("");
    try { const response = await chat.mutateAsync({ message: trimmed, language: state.language, profile: profileSummary }); addAssistantMessage({ id: `assistant-${Date.now()}`, role: "assistant", content: response.reply, createdAt: new Date().toISOString() }); }
    catch { addAssistantMessage({ id: `assistant-${Date.now()}`, role: "assistant", content: state.language === "hi" ? "अभी कनेक्शन उपलब्ध नहीं है। आप Discover में course या category से खोज सकते हैं और Document Vault में सामान्य दस्तावेज़ तैयार कर सकते हैं।" : "I can’t reach the guidance service right now. You can still use Discover to search by course or category and prepare common records in Document Vault.", createdAt: new Date().toISOString() }); }
  };
  return <SathiScreen><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView contentContainerStyle={[sharedStyles.content, styles.chatContent]} keyboardShouldPersistTaps="handled"><PageHeader eyebrow="Hindi / English guidance" title="Ask Sathi" /><View style={[styles.notice, { backgroundColor: "#EAF2FF" }]}><MaterialIcons name="smart-toy" size={21} color={colors.primary} /><Text style={[styles.noticeText, { color: colors.foreground }]}>Sathi provides planning guidance using your local profile. It does not verify live schemes or replace official provider criteria.</Text></View><ScrollView contentContainerStyle={styles.messageList}>{state.assistantMessages.map((item) => <View key={item.id} style={[styles.message, item.role === "user" ? [styles.userMessage, { backgroundColor: colors.primary }] : [styles.assistantMessage, { backgroundColor: colors.surface, borderColor: colors.border }]]}><Text style={[styles.messageText, { color: item.role === "user" ? colors.background : colors.foreground }]}>{item.content}</Text></View>)}{chat.isPending ? <View style={[styles.typing, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.typingText, { color: colors.muted }]}>Sathi is thinking…</Text></View> : null}</ScrollView><Text style={[styles.suggestionLabel, { color: colors.muted }]}>TRY ASKING</Text><View style={styles.promptRow}>{PROMPTS.map((prompt) => <Chip key={prompt} label={prompt} onPress={() => send(prompt)} />)}</View></ScrollView><View style={[styles.composer, { backgroundColor: colors.background, borderTopColor: colors.border }]}><TextInput value={message} onChangeText={setMessage} placeholder={state.language === "hi" ? "अपना प्रश्न लिखें" : "Ask about scholarships or documents"} placeholderTextColor={colors.muted} style={[styles.composerInput, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]} multiline /><Pressable disabled={!message.trim() || chat.isPending} onPress={() => send()} style={({ pressed }) => [styles.sendButton, { backgroundColor: message.trim() && !chat.isPending ? colors.primary : colors.border }, pressed && styles.pressed]}><MaterialIcons name="arrow-upward" size={21} color={colors.background} /></Pressable></View></KeyboardAvoidingView></SathiScreen>;
}

const styles = StyleSheet.create({
  flex: { flex: 1 }, chatContent: { paddingBottom: 20 }, notice: { borderRadius: 18, padding: 14, flexDirection: "row", gap: 10 }, noticeText: { flex: 1, fontSize: 12, lineHeight: 17, fontWeight: "600" }, messageList: { paddingTop: 18, gap: 10 }, message: { maxWidth: "88%", borderRadius: 18, paddingVertical: 11, paddingHorizontal: 13 }, assistantMessage: { alignSelf: "flex-start", borderWidth: 1 }, userMessage: { alignSelf: "flex-end" }, messageText: { fontSize: 14, lineHeight: 20 }, typing: { alignSelf: "flex-start", borderWidth: 1, borderRadius: 18, paddingVertical: 11, paddingHorizontal: 13 }, typingText: { fontSize: 13, fontWeight: "700" }, suggestionLabel: { fontSize: 10, fontWeight: "800", letterSpacing: 0.8, marginTop: 22, marginBottom: 9 }, promptRow: { flexDirection: "row", flexWrap: "wrap", gap: 0 }, composer: { borderTopWidth: 1, flexDirection: "row", paddingHorizontal: 20, paddingTop: 10, paddingBottom: 12, gap: 9, alignItems: "flex-end" }, composerInput: { flex: 1, minHeight: 47, maxHeight: 110, borderWidth: 1, borderRadius: 16, paddingHorizontal: 13, paddingTop: 12, fontSize: 14, textAlignVertical: "top" }, sendButton: { width: 47, height: 47, borderRadius: 15, alignItems: "center", justifyContent: "center" }, pressed: { opacity: 0.75, transform: [{ scale: 0.98 }] },
});
