import type { CommunityPost, NewsItem, Scholarship } from "./studentsathi";

export const SCHOLARSHIPS: Scholarship[] = [
  {
    id: "saksham-futures",
    title: "Saksham Futures Grant",
    provider: "StudentSathi demo catalogue",
    type: "Private",
    award: "Up to ₹45,000",
    deadline: "2026-10-15",
    description: "A sample needs-aware undergraduate support listing for exploring StudentSathi’s matching and application tools.",
    states: ["All India"],
    courses: ["Any course"],
    categories: ["All categories"],
    incomeBands: ["under-2", "2-to-5"],
    gender: "all",
    educationLevels: ["Undergraduate", "Diploma"],
    requiredDocuments: ["Identity proof", "Academic marksheet", "Income certificate", "Bank details"],
    tags: ["Need based", "Undergraduate", "Popular"],
  },
  {
    id: "nayi-udaan-stem",
    title: "Nayi Udaan STEM Scholarship",
    provider: "StudentSathi demo catalogue",
    type: "Private",
    award: "Up to ₹60,000",
    deadline: "2026-11-08",
    description: "A sample women-in-STEM opportunity that demonstrates transparent profile matching and document preparation.",
    states: ["All India"],
    courses: ["Engineering", "Science", "Computer Science"],
    categories: ["All categories"],
    incomeBands: ["under-2", "2-to-5", "5-to-8"],
    gender: "female",
    educationLevels: ["Undergraduate", "Postgraduate"],
    requiredDocuments: ["Identity proof", "Academic marksheet", "Income certificate", "Bank details"],
    tags: ["Women students", "STEM", "Merit based"],
  },
  {
    id: "campus-continuity",
    title: "Campus Continuity Fund",
    provider: "StudentSathi demo catalogue",
    type: "College",
    award: "Fee support varies",
    deadline: "2026-09-30",
    description: "A sample college-linked fee-assistance listing for students managing an active academic year.",
    states: ["All India"],
    courses: ["Any course"],
    categories: ["All categories"],
    incomeBands: ["under-2", "2-to-5"],
    gender: "all",
    educationLevels: ["Undergraduate", "Postgraduate", "Diploma"],
    requiredDocuments: ["Identity proof", "Academic marksheet", "Income certificate"],
    tags: ["Fee assistance", "College", "Closing soon"],
  },
  {
    id: "krishi-vidya",
    title: "Krishi Vidya Learner Support",
    provider: "StudentSathi demo catalogue",
    type: "Government",
    award: "Support amount varies",
    deadline: "2026-12-01",
    description: "A sample farmer-family support listing that illustrates additional eligibility criteria and document reminders.",
    states: ["All India"],
    courses: ["Any course"],
    categories: ["All categories"],
    incomeBands: ["under-2", "2-to-5", "5-to-8"],
    gender: "all",
    requiresFarmerFamily: true,
    educationLevels: ["Undergraduate", "Diploma", "School"],
    requiredDocuments: ["Identity proof", "Academic marksheet", "Income certificate", "Bank details"],
    tags: ["Farmer family", "Government", "Need based"],
  },
];

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: "news-1",
    category: "Scholarships",
    title: "Plan a clean document folder before applications open",
    summary: "Use the document vault to check common requirements and flag records that need updating.",
    updatedLabel: "StudentSathi guide",
    important: true,
  },
  {
    id: "news-2",
    category: "Admissions",
    title: "Keep official admission notices alongside your application notes",
    summary: "A simple notes trail helps you compare eligibility wording and application deadlines later.",
    updatedLabel: "StudentSathi guide",
  },
  {
    id: "news-3",
    category: "Internships",
    title: "Build an opportunity list that includes funding and skills",
    summary: "Use your saved list to separate scholarships, internships, and future certification opportunities.",
    updatedLabel: "StudentSathi guide",
  },
];

export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "community-1",
    author: "A StudentSathi learner",
    title: "How do you keep documents ready before applying?",
    body: "I start with identity, marksheet, income proof, and bank details, then check the exact provider instructions.",
    tags: ["Documents", "Applications"],
    helpfulCount: 0,
    createdLabel: "Community starter discussion",
  },
  {
    id: "community-2",
    author: "A StudentSathi learner",
    title: "What should I verify before trusting a scholarship link?",
    body: "Check the provider name, official site, eligibility text, deadline, and whether the application page is secure.",
    tags: ["Safety", "Discovery"],
    helpfulCount: 0,
    createdLabel: "Community starter discussion",
  },
];
